services:
  icecast-exporter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    image: ls11-icecast-exporter:latest
    container_name: ls11-icecast-exporter-${SERVICE_NAME:-icecast}
    environment:
      - ICECAST_URL=${ICECAST_URL}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-30s}
      - WEB_LISTEN_ADDRESS=${WEB_LISTEN_ADDRESS:-:9146}
      - WEB_TELEMETRY_PATH=${WEB_TELEMETRY_PATH:-/metrics}
    ports:
      - "${PORT:-9146}:9146"
    restart: unless-stopped
    extra_hosts:
      - "streaming.provinciaradio.com.ar:${ICECAST_INTERNAL_IP}"
    command:
      - -icecast.scrape-uri=${ICECAST_URL}
      - -icecast.timeout=${SCRAPE_INTERVAL}
      - -web.listen-address=${WEB_LISTEN_ADDRESS}
      - -web.telemetry-path=${WEB_TELEMETRY_PATH}